---
# Service object for routing requests to deno.land
apiVersion: v1
kind: Service
metadata:
  name: deno
  namespace: tool-deno
spec:
  type: ExternalName
  externalName: cdn.deno.land
...
---
# Ingress object for routing requests to deno.land
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-deno
  namespace: tool-deno
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/upstream-vhost: cdn.deno.land
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name cdn.deno.land;
      proxy_ssl_server_name on;
spec:
  rules:
    - host: deno.toolforge.org
      http:
        paths:
          - backend:
              serviceName: deno
              servicePort: 443
            path: /deno(/|$)(.*)
...
